config/routes.rb
Rails.application.routes.draw do
  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id           :integer          not null, primary key
#  make         :string           not null
#  model        :string           not null
#  year         :integer          not null
#  vin          :string           not null
#  color        :string           default("black")
#  category     :string           default("car")
#  cylinders    :integer          default(4)
#  displacement :float            default(0.0)
#  mpg          :integer          default(0)
#  hp           :integer          default(0)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Car < ApplicationRecord
  before_validation :upper, :check_vin

  validates :make, :model, :year, :vin, presence: true
  validates :vin, length: {is: 17}
  validates :vin, uniqueness: true
  validates :make, uniqueness: {scope: [:model, :year]}
  validates :year, inclusion: {in: 1900..2020, message: 'is not between 1900 and 2020'}
  validates :category, inclusion: {in: ['CAR', 'SPORT', 'SUV', 'TRUCK']}
  validates :cylinders, inclusion: {in: [4, 6, 8, 12], message: 'is not one of 4, 6, 8 or 12'}

  private

  def upper
    self.vin = self.vin.upcase if self.vin
    self.category = self.category.upcase if self.category
  end

  def check_vin
    self.errors.add(:vin, 'invalid representation') if self.vin && self.vin !~ /^[0-9A-Z]{17}$/
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end
  
 def show
    @car = Car.find(params[:id])
 end
 
 def destroy
     car = Car.find(params[:id])
     car.destroy
     redirect_to cars_path
 end
 
 def new
    @car = Car.new
 end
 
 def create
     @car = Car.new(params[:car].permit(:vin, :make, :model, :year))
     if @car.save
         redirect_to @car
     else
         render 'new'
     end
 end
 
 def edit
    @car = Car.find(params[:id])
 end
 
 def update
 end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= form_with(model: @car, local: true) do |form| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vin %>
    <%= form.text_field :vin, id: :car_vin %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make, id: :car_make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :car_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/index.html.erb
<h1>Cars</h1>

<%= link_to 'New', new_car_path %>

<table>
  <thead>
    <tr>
      <th>Vin</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |c| %>
      <tr>
        <td><%= link_to c.vin, c %></td>
        <td><%= c.make %></td>
        <td><%= c.model %></td>
        <td><%= c.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= form_with(model: @car, local: true) do |form| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vin %>
    <%= form.text_field :vin, id: :car_vin %>
  </div>

  <div class="field">
    <%= form.label :make %>
    <%= form.text_field :make, id: :car_make %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :car_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/show.html.erb
<h1>Car</h1>

<%= link_to 'Edit', edit_car_path(@car) %>
<%= link_to 'Delete', @car, method: :delete %>

<table class="table table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>Vin</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      </tr>
  </thead>
  <tbody>
 
      <tr>
        <td><%= @car.vin %></td>
        <td><%= @car.make %></td>
        <td><%= @car.model %></td>
        <td><%= @car.year %></td>
      </tr>
     
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dealer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>